dubbo:
  config:
    multiple: true
  registries:
    prod:
      id: prod
      address: 192.168.7.1:2181
      protocol: zookeeper
      check: false
      default: true
    gray:
      id: gray
      address: 115.159.144.187:2181,115.159.144.187:2182,115.159.144.187:2183
      protocol: zookeeper
      check: false
  application:
    name: provider-demo
#  registry:
#    address: 192.168.7.1:2181
#    protocol: zookeeper
#    #    address: 192.168.7.1:8848
#    #    protocol: nacos
#    check: false # true注册订阅失败时报错
  protocol:
    id: dubbo
    name: dubbo #协议名称
    port: 28081 #服务端口
    threadpool: fixed #线程池类型，可选：fixed/cached
    threads: 200 #服务线程池大小(固定大小)
    payload: 8388608 #请求及响应数据包大小限制，单位：字节
  consumer:
    timeout: 5000 # 调用服务超时时间  reference > service > consumer > provider
    retries: 2 # 不包含第一次调用
    check: false # 启动时检查提供者是否存在，true报错，false忽略
    loadbalance: roundrobin #负载均衡策略，可选值：random,roundrobin,leastactive，分别表示：随机，轮询，最少活跃调用
  provider:
    timeout: 5000 #调用服务超时时间
    retries: 0 #远程服务调用重试次数，不包括第一次调用，不需要重试请设为0
    parameters:
      profile: gray
server:
  port: 7001  #如果部署多台 端口不同重复
spring:
  redis:
    host: 192.168.7.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 10
        max-wait: 5000